### ISSUE TITLE
Agree on basic project things

### ISSUE THREAD

**Issue by leowroth** [weg-li/weg-li-android#1]
- [ ] MVVM, MVP ... something else?
- [ ] Codestyle
- [ ] Testing?
- [ ] Code review for every issue?
- [ ] license?
- [ ] check https://opensource.guide/starting-a-project/

**Comment by Rembremmerdeng** [comment]
Do you agree on excluding all Google Play Services? It's the only way to get it on F-Droid and use it on custom Androids and because of https://fossbytes.com/wp-content/uploads/2018/09/Google-Alternatives.jpg

However it means maybe some more effort, e. g. using Mapsforge https://github.com/mapsforge/mapsforge instead of Google Maps SDK.

**Comment by Rembremmerdeng** [comment]
MVVM sounds better than MVP for this project
Codestyle? Common Android best practice.
Testing? Where necessary. Don't over-engineer it.
Code review? Agreed.
License? I would suggest MIT (do whatever you want) or GPL (you have to make it free as well).

**Comment by leowroth** [comment]
> Do you agree on excluding all Google Play Services? It's the only way to get it on F-Droid and use it on custom Androids and because of https://fossbytes.com/wp-content/uploads/2018/09/Google-Alternatives.jpg
> 
> However it means maybe some more effort, e. g. using Mapsforge https://github.com/mapsforge/mapsforge instead of Google Maps SDK.

I believe this should be possible. Let's look at this problem, when one of us does the map part.

**Comment by leowroth** [comment]
> Codestyle? Common Android best practice.
We should agree on a codestyle file and then automatically run it with every commit. The benefit is, that we won't push commits later with changes that are just different tabs and blanks etc.

I'll have a quick look at it and will add it to the project.
